// clang-format off
#if __has_include(<unistd.h>)
#include <unistd.h>
#endif
#if __has_include(<io.h>)
#include <io.h>
#endif
#if defined(_WIN32)
#include <immintrin.h>
#elif defined(__ARM_NEON) || defined(__ARM_NEON__)
#include <arm_neon.h>
#endif

#include <map>
#include <set>
#include <iostream>
#include <deque>
#include <optional>
#include <variant>
#include <filesystem>
#include <cassert>
#include <format>
#include <regex>
#include <chrono>
#include <array>
#include <unordered_map>
#include <functional>

#include "Status.hpp"
#include "Optional.hpp"

#include "Type.hpp"
#include "gfx/Transform.hpp"
#include "gfx/Vec.hpp"
#include "gfx/Rect.hpp"
#include "gfx/Point.hpp"
#include "gfx/Line.hpp"
#include "gfx/QuadraticEquation.hpp"
#include "gfx/QuadraticBezier.hpp"
#include "gfx/Path.hpp"
#include "gfx/Shape.hpp"
#include "io/Endianness.hpp"
#include "io/InputStream.hpp"
#include "io/OutputStream.hpp"
#include "io/OffsetInputStream.hpp"
#include "io/File.hpp"
#include "io/FileInputStream.hpp"
#include "io/FileOutputStream.hpp"
#include "io/ByteInputStream.hpp"
#include "io/ByteOutputStream.hpp"
#include "io/OffsetWriter.hpp"
#include "io/DataFragmentWriter.hpp"
#include "Tag.hpp"
#include "Unicode.hpp"
#include "TableRecord.hpp"
#include "TableDirectory.hpp"
#include "table/Table.hpp"
#include "table/ReadonlyTable.hpp"
#include "table/head/FontHeaderTable.hpp"
#include "table/maxp/MaximumProfileTable.hpp"
#include "table/loca/IndexToLocationTable.hpp"
#include "table/glyf/GlyphDataTable.hpp"
#include "table/post/PostScriptTable.hpp"
#include "table/os2/OS2AndWindowsMetricsTable.hpp"
#include "table/hhea/HorizontalHeaderTable.hpp"
#include "table/hmtx/HorizontalMetricsTable.hpp"
#include "table/g/ScriptList.hpp"
#include "table/g/FeatureList.hpp"
#include "table/g/LookupList.hpp"
#include "table/g/FeatureVariations.hpp"
#include "table/Coverage.hpp"
#include "table/ClassDef.hpp"
#include "table/g/Subtable.hpp"
#include "table/g/SubtableCollection.hpp"
#include "table/g/SequenceLookup.hpp"
#include "table/gdef/MarkGlyphSets.hpp"
#include "table/g/Contextual.hpp"
#include "table/g/ChainedContexts.hpp"
#include "table/g/sub/Single.hpp"
#include "table/g/sub/Ligature.hpp"
#include "table/g/sub/Multiple.hpp"
#include "table/g/sub/ReverseChainedContextsSingle.hpp"
#include "table/g/sub/Alternate.hpp"
#include "table/g/sub/SubstitutionExtension.hpp"
#include "table/g/pos/Anchor.hpp"
#include "table/g/pos/Attachment.hpp"
#include "table/g/pos/MarkArray.hpp"
#include "table/g/pos/ValueRecord.hpp"
#include "table/g/pos/SingleAdjustment.hpp"
#include "table/g/pos/PairAdjustment.hpp"
#include "table/g/pos/CursiveAttachment.hpp"
#include "table/g/pos/MarkToBaseAttachment.hpp"
#include "table/g/pos/MarkToLigatureAttachment.hpp"
#include "table/g/pos/MarkToMarkAttachment.hpp"
#include "table/g/pos/PositioningExtension.hpp"
#include "table/g/sub/GlyphSubstitutionTable.hpp"
#include "table/g/pos/GlyphPositioningTable.hpp"
#include "table/gdef/GlyphDefinitionTable.hpp"
#include "table/vhea/VerticalHeaderTable.hpp"
#include "table/vmtx/VerticalMetricsTable.hpp"
#include "table/cmap/CmapSubtable.hpp"
#include "table/cmap/ByteEncoding.hpp"
#include "table/cmap/SegmentMappingToDeltaValues.hpp"
#include "table/cmap/TrimmedTableMapping.hpp"
#include "table/cmap/SegmentedCoverage.hpp"
#include "table/cmap/UnicodeVariationSequences.hpp"
#include "table/cmap/CharacterToGlyphIndexMappingTable.hpp"
#include "table/name/NamingTable.hpp"
#include "table/cff/Type.hpp"
#include "table/cff/Index.hpp"
#include "table/cff/Dict.hpp"
#include "table/cff/StdStrings.hpp"
#include "table/cff/CompactFontFormatTable.hpp"
#include "Font.hpp"
#include "GlyphNames.hpp"
#include "editor/PlaceholderGlyph.hpp"
#include "editor/CartoucheGlyph.hpp"
#include "editor/ShadingGlyph.hpp"
#include "editor/Glyph.hpp"
#include "editor/Group.hpp"
#include "editor/SizeVariants.hpp"
#include "editor/Insertion.hpp"
#include "editor/Config.hpp"
#include "editor/Editor.hpp"
#include "editor/VtpParser.hpp"
#include "editor/Vtp.hpp"
#include "glyph/BasicGlyphs.hpp"
#include "editor/Transformer.hpp"
