// clang-format off
#if __has_include(<unistd.h>)
#include <unistd.h>
#endif
#if __has_include(<io.h>)
#include <io.h>
#endif
#if defined(_WIN32)
#include <immintrin.h>
#elif defined(__ARM_NEON) || defined(__ARM_NEON__)
#include <arm_neon.h>
#endif

#include <map>
#include <set>
#include <iostream>
#include <deque>
#include <optional>
#include <variant>
#include <filesystem>
#include <cassert>
#include <format>
#include <regex>
#include <chrono>
#include <array>
#include <unordered_map>
#include <unordered_set>
#include <functional>

#include "../src/Status.hpp"
#include "../src/Optional.hpp"

#include "../src/Type.hpp"
#include "../src/gfx/Transform.hpp"
#include "../src/gfx/Vec.hpp"
#include "../src/gfx/Rect.hpp"
#include "../src/gfx/Point.hpp"
#include "../src/gfx/Line.hpp"
#include "../src/gfx/QuadraticEquation.hpp"
#include "../src/gfx/QuadraticBezier.hpp"
#include "../src/gfx/Path.hpp"
#include "../src/gfx/Shape.hpp"
#include "../src/io/Endianness.hpp"
#include "../src/io/InputStream.hpp"
#include "../src/io/OutputStream.hpp"
#include "../src/io/OffsetInputStream.hpp"
#include "../src/io/File.hpp"
#include "../src/io/FileInputStream.hpp"
#include "../src/io/FileOutputStream.hpp"
#include "../src/io/ByteInputStream.hpp"
#include "../src/io/ByteOutputStream.hpp"
#include "../src/io/OffsetWriter.hpp"
#include "../src/io/DataFragmentWriter.hpp"
#include "../src/Tag.hpp"
#include "../src/Unicode.hpp"
#include "../src/unikemet/Unikemet.hpp"
#include "../src/TableRecord.hpp"
#include "../src/TableDirectory.hpp"
#include "../src/table/Table.hpp"
#include "../src/table/ReadonlyTable.hpp"
#include "../src/table/head/FontHeaderTable.hpp"
#include "../src/table/maxp/MaximumProfileTable.hpp"
#include "../src/table/loca/IndexToLocationTable.hpp"
#include "../src/table/glyf/GlyphDataTable.hpp"
#include "../src/table/post/PostScriptTable.hpp"
#include "../src/table/os2/OS2AndWindowsMetricsTable.hpp"
#include "../src/table/hhea/HorizontalHeaderTable.hpp"
#include "../src/table/hmtx/HorizontalMetricsTable.hpp"
#include "../src/table/g/ScriptList.hpp"
#include "../src/table/g/FeatureList.hpp"
#include "../src/table/g/LookupList.hpp"
#include "../src/table/g/FeatureVariations.hpp"
#include "../src/table/Coverage.hpp"
#include "../src/table/ClassDef.hpp"
#include "../src/table/g/Subtable.hpp"
#include "../src/table/g/SubtableCollection.hpp"
#include "../src/table/g/SequenceLookup.hpp"
#include "../src/table/gdef/MarkGlyphSets.hpp"
#include "../src/table/g/Contextual.hpp"
#include "../src/table/g/ChainedContexts.hpp"
#include "../src/table/g/sub/Single.hpp"
#include "../src/table/g/sub/Ligature.hpp"
#include "../src/table/g/sub/Multiple.hpp"
#include "../src/table/g/sub/ReverseChainedContextsSingle.hpp"
#include "../src/table/g/sub/Alternate.hpp"
#include "../src/table/g/sub/SubstitutionExtension.hpp"
#include "../src/table/g/pos/Anchor.hpp"
#include "../src/table/g/pos/Attachment.hpp"
#include "../src/table/g/pos/MarkArray.hpp"
#include "../src/table/g/pos/ValueRecord.hpp"
#include "../src/table/g/pos/SingleAdjustment.hpp"
#include "../src/table/g/pos/PairAdjustment.hpp"
#include "../src/table/g/pos/CursiveAttachment.hpp"
#include "../src/table/g/pos/MarkToBaseAttachment.hpp"
#include "../src/table/g/pos/MarkToLigatureAttachment.hpp"
#include "../src/table/g/pos/MarkToMarkAttachment.hpp"
#include "../src/table/g/pos/PositioningExtension.hpp"
#include "../src/table/g/sub/GlyphSubstitutionTable.hpp"
#include "../src/table/g/pos/GlyphPositioningTable.hpp"
#include "../src/table/gdef/GlyphDefinitionTable.hpp"
#include "../src/table/vhea/VerticalHeaderTable.hpp"
#include "../src/table/vmtx/VerticalMetricsTable.hpp"
#include "../src/table/cmap/CmapSubtable.hpp"
#include "../src/table/cmap/ByteEncoding.hpp"
#include "../src/table/cmap/SegmentMappingToDeltaValues.hpp"
#include "../src/table/cmap/TrimmedTableMapping.hpp"
#include "../src/table/cmap/SegmentedCoverage.hpp"
#include "../src/table/cmap/UnicodeVariationSequences.hpp"
#include "../src/table/cmap/CharacterToGlyphIndexMappingTable.hpp"
#include "../src/table/name/NamingTable.hpp"
#include "../src/table/cff/Type.hpp"
#include "../src/table/cff/Index.hpp"
#include "../src/table/cff/Dict.hpp"
#include "../src/table/cff/StdStrings.hpp"
#include "../src/table/cff/CompactFontFormatTable.hpp"
#include "../src/Font.hpp"
#include "../src/GlyphNames.hpp"
#include "../src/editor/PlaceholderGlyph.hpp"
#include "../src/editor/CartoucheGlyph.hpp"
#include "../src/editor/ShadingGlyph.hpp"
#include "../src/editor/BracketGlyph.hpp"
#include "../src/editor/Glyph.hpp"
#include "../src/editor/Group.hpp"
#include "../src/editor/SizeVariants.hpp"
#include "../src/editor/Insertion.hpp"
#include "../src/editor/Config.hpp"
#include "../src/glyph/BasicGlyphs.hpp"
#include "../src/editor/Editor.hpp"
#include "../src/editor/VtpParser.hpp"
#include "../src/editor/Vtp.hpp"
#include "../src/editor/Transformer.hpp"
